In [22]:
import numpy
import tensorflow as tf
from numpy import array
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding

In [23]:
# 텍스트 리뷰 자료 지정
docs = ['너무 재밌네요', '최고에요', '참 잘 만든 영화에요', '추천하고 싶은 영화입니다.',
        '한번 더 보고싶네요', '글쎄요', '별로에요', '생각보다 지루하네요', '연기가 어색해요',
        '재미없어요']

In [24]:
# 긍정 리뷰는 1. 부정 리뷰는 0으로 클래스 지정
classes = array([1,1,1,1,1,0,0,0,0,0])

In [25]:
# 토큰화
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고에요': 3, '참': 4, '잘': 5, '만든': 6, '영화에요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로에요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [26]:
x = token.texts_to_sequences(docs)
print("\n리뷰 텍스트, 토큰화 결과:\n",  x)


리뷰 텍스트, 토큰화 결과:
 [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]


In [27]:
# 패딩. 서로 다른 길이의 데이터를 4로 맞춤
padded_x = pad_sequences(x, 4)
"\n패딩 결과\n", print(padded_x)

[[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


('\n패딩 결과\n', None)

In [28]:
# 임베딩에 입력될 단어 수 지정
word_size = len(token.word_index)+1

In [30]:
# 단어 임베딩을 포함하여 딥러닝 모델을 만들고 결과 출력
model = Sequential()
model.add(Embedding(word_size, 8, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.compile(optmizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(padded_x, classes, epochs=20)

print("\n Accuracy: %.4f" % (model.evaluate(padded_x, classes)[1]))

Train on 10 samples
Epoch 1/20
10/10 [==============================] - 0s 48ms/sample - loss: 0.6995 - accuracy: 0.3000
Epoch 2/20
10/10 [==============================] - 0s 200us/sample - loss: 0.6923 - accuracy: 0.5000
Epoch 3/20
10/10 [==============================] - 0s 100us/sample - loss: 0.6871 - accuracy: 0.6000
Epoch 4/20
10/10 [==============================] - 0s 100us/sample - loss: 0.6827 - accuracy: 0.6000
Epoch 5/20
10/10 [==============================] - 0s 100us/sample - loss: 0.6788 - accuracy: 0.7000
Epoch 6/20
10/10 [==============================] - 0s 200us/sample - loss: 0.6752 - accuracy: 0.9000
Epoch 7/20
10/10 [==============================] - 0s 100us/sample - loss: 0.6718 - accuracy: 0.9000
Epoch 8/20
10/10 [==============================] - 0s 100us/sample - loss: 0.6686 - accuracy: 0.9000
Epoch 9/20
10/10 [==============================] - 0s 100us/sample - loss: 0.6655 - accuracy: 1.0000
Epoch 10/20
10/10 [==============================] - 0s 100us/s